### ISSUE TITLE
Error EISDIR at startup

### ISSUE THREAD

**Issue by mmailhos** [astzweig/docker-wildduck#16]
Hello, thanks for the awesome project!

I have been trying to start it on 2 different machines (OSX 10.15 and Ubuntu 18:04, Docker Engine 19.03.8) and I have had the same error with the two docker-compose:

```
mail_1   | info SMTP/feeder SMTP feeder MTA server started listening on port 465
mail_1   | info QS Queue server started
mail_1   | info API API server started
mail_1   | info Redis/1264 Redis ready to take connections
mail_1   | internal/fs/utils.js:220
mail_1   |     throw err;
mail_1   |     ^
mail_1   |
mail_1   | Error: EISDIR: illegal operation on a directory, read
mail_1   |     at Object.readSync (fs.js:506:3)
mail_1   |     at tryReadSync (fs.js:331:20)
mail_1   |     at Object.readFileSync (fs.js:368:19)
mail_1   |     at /var/nodemailer/wildduck/lib/certs.js:37:22
mail_1   |     at Array.forEach (<anonymous>)
mail_1   |     at Object.module.exports.reload (/var/nodemailer/wildduck/lib/certs.js:11:64)
mail_1   |     at Object.<anonymous> (/var/nodemailer/wildduck/lib/certs.js:71:16)
mail_1   |     at Module._compile (internal/modules/cjs/loader.js:955:30)
mail_1   |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
mail_1   |     at Module.load (internal/modules/cjs/loader.js:811:32) {
mail_1   |   errno: -21,
mail_1   |   syscall: 'read',
mail_1   |   code: 'EISDIR'
mail_1   | }
```

Does anyone know how to get around this issue?

It also seems there are some issues when building the image (probably due to the alpine image `latest` referring to a different image as the one initially used?).

```
ERROR: unsatisfiable constraints:
  python (missing):
    required by: git-20200613.133430[python]
ERROR: Service 'mail' failed to build: The command '/bin/sh -c for file in ${SCRIPTS_DIR}/[0-9][0-9]-*.sh; do         chmod u+x "${file}";         source "${file}";     done' returned a non-zero code: 2
```

**Comment by mmailhos** [comment]
The first error can be fixed by generating the TLS key-pair.
The build error can be fixed by removing the virtual build-deps and installing pip3 with:

```
apk add --no-cache python3-dev libffi-dev openssl-dev && \
    pip3 install --upgrade pip setuptools
```

**Comment by rqelibari** [comment]
@mmailhos Thanks for fixing the issue. Do you want to prepare a PR for it?
